# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_metadata_pb2 as file__metadata__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_metadata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileMetadataServiceStub(object):
    """gRPC Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadMetadata = channel.unary_unary(
                '/filemetadata.FileMetadataService/UploadMetadata',
                request_serializer=file__metadata__pb2.FileMetadata.SerializeToString,
                response_deserializer=file__metadata__pb2.Empty.FromString,
                _registered_method=True)
        self.ListMetadata = channel.unary_stream(
                '/filemetadata.FileMetadataService/ListMetadata',
                request_serializer=file__metadata__pb2.Empty.SerializeToString,
                response_deserializer=file__metadata__pb2.FileMetadata.FromString,
                _registered_method=True)
        self.GetMetadataByName = channel.unary_unary(
                '/filemetadata.FileMetadataService/GetMetadataByName',
                request_serializer=file__metadata__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=file__metadata__pb2.FileMetadata.FromString,
                _registered_method=True)


class FileMetadataServiceServicer(object):
    """gRPC Service Definition
    """

    def UploadMetadata(self, request, context):
        """Upload a file's metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMetadata(self, request, context):
        """Get metadata for all files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadataByName(self, request, context):
        """Get metadata for a specific file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileMetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadMetadata,
                    request_deserializer=file__metadata__pb2.FileMetadata.FromString,
                    response_serializer=file__metadata__pb2.Empty.SerializeToString,
            ),
            'ListMetadata': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMetadata,
                    request_deserializer=file__metadata__pb2.Empty.FromString,
                    response_serializer=file__metadata__pb2.FileMetadata.SerializeToString,
            ),
            'GetMetadataByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadataByName,
                    request_deserializer=file__metadata__pb2.GetMetadataRequest.FromString,
                    response_serializer=file__metadata__pb2.FileMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filemetadata.FileMetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('filemetadata.FileMetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileMetadataService(object):
    """gRPC Service Definition
    """

    @staticmethod
    def UploadMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filemetadata.FileMetadataService/UploadMetadata',
            file__metadata__pb2.FileMetadata.SerializeToString,
            file__metadata__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filemetadata.FileMetadataService/ListMetadata',
            file__metadata__pb2.Empty.SerializeToString,
            file__metadata__pb2.FileMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadataByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filemetadata.FileMetadataService/GetMetadataByName',
            file__metadata__pb2.GetMetadataRequest.SerializeToString,
            file__metadata__pb2.FileMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
