# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_metadata.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'file_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_metadata.proto\x12\x0c\x66ilemetadata\"G\n\x0c\x46ileMetadata\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_size\x18\x02 \x01(\x03\x12\x11\n\tfile_type\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"\'\n\x12GetMetadataRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"9\n\x0cMetadataList\x12)\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x1a.filemetadata.FileMetadata2\xee\x01\n\x13\x46ileMetadataService\x12\x41\n\x0eUploadMetadata\x12\x1a.filemetadata.FileMetadata\x1a\x13.filemetadata.Empty\x12\x41\n\x0cListMetadata\x12\x13.filemetadata.Empty\x1a\x1a.filemetadata.FileMetadata0\x01\x12Q\n\x11GetMetadataByName\x12 .filemetadata.GetMetadataRequest\x1a\x1a.filemetadata.FileMetadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEMETADATA']._serialized_start=37
  _globals['_FILEMETADATA']._serialized_end=108
  _globals['_EMPTY']._serialized_start=110
  _globals['_EMPTY']._serialized_end=117
  _globals['_GETMETADATAREQUEST']._serialized_start=119
  _globals['_GETMETADATAREQUEST']._serialized_end=158
  _globals['_METADATALIST']._serialized_start=160
  _globals['_METADATALIST']._serialized_end=217
  _globals['_FILEMETADATASERVICE']._serialized_start=220
  _globals['_FILEMETADATASERVICE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
